items = {
        ### Velious Armor Gems Start
        "Flawless Diamond": "Melee BP 3k",
        "Flawed Sea Sapphire": "Melee Legs 100p",
        "Flawed Emerald": "Melee Arms 100p",
        "Crushed Coral": "Melee Helms 100p",
        "Crushed Topaz": "Melee/Caster: Gloves 100p",
        "Crushed Black Marble": "Melee Boots 100p",
        "Crushed Flame Emerald": "Melee Bracer/Priest Boots 500p",
        "Black Marble": "Priest BP 1k(NOT Chipped!) ",
        "Chipped Onyx Sapphire": "Priest Legs 100p",
        "Crushed Jaundice Gem": "Caster Boots 100p",
        "Jaundice Gem": "Priest Arms 100p",
        "Crushed Lava Ruby": "Priest Gloves 100p",
        "Crushed Opal": "Priest Bracer 100p",
        "Crushed Onyx Sapphire": "Caster Bracer/Priest Helm 100p",
        "Pristine Emerald": "Caster Robe 300p",
        "Nephrite": "Caster Legs 100p",
        "Flawed Topaz": "Caster Arms 100p",
        "Crushed Flame Opal": "Caster Helm 100p",
        ### JC Gems Start
        "Black Perl": "JC 40p",
        "Black Sapphire": "JC/Quests 250p",
        "Fire Opal": "JC/Quests 50p",
        "Jacinth": "JC/Quests 200p",
        "Blue Diamond": "JC 300p",
        "Diamond": "JC/Quests 250p",
        ### Spell Research
        ### Enchanter
        "Part of Tasarin's Grimoire Pg. 26": "enc Lvl 16 Mesmerization",
        "Part of Tasarin's Grimoire Pg. 30": "enc Lvl 20 Berserker Strength",
        "Part of Tasarin's Grimoire Pg. 312": "enc Lvl 20 Color Shift",
        "Part of Tasarin's Grimoire Pg. 390": "enc Lvl 24 Strip Enchanment",
        "Velishoul's Tome Pg. 8": "enc Lvl 24 Tepid Deeds",
        "Velishoul's Tome Pg. 9": "enc Lvl 24 Tepid Deeds",
        "Velishoul's Tome Pg. 108": "enc Lvl 29 Feedback",
        "Velishoul's Tome Pg. 109": "enc Lvl 29 Feedback",
        "Salil's Writ Pg. 60": "enc Lvl 34 Insipid Weakness",
        "Salil's Writ Pg. 64": "enc Lvl 34 Radiant Visage",
        "Salil's Writ Pg. 90": "enc Lvl 34 Mana Sieve",
        "Salil's Writ Pg. 174": "enc Lvl 39 Gravity FLux",
        "Salil's Writ Pg. 288": "enc Lvl 39 Mind Wipe",
        "Nilitim's Grimoire Pg. 35": "enc Lvl 44 Pillage Enchantment",
        "Nilitim's Grimoire Pg. 36": "enc Lvl 44 Pillage Enchantment",
        "Nilitim's Grimoire Pg. 115": "enc Lvl 44 Color Skew",
        "Nilitim's Grimoire Pg. 116": "enc Lvl 44 Color Skew",
        "Nilitim's Grimoire Pg. 300": "ENC Lvl 44 Shiftless Deeds",
        "Nilitim's Grimoire Pg. 301": "enc Lvl 44 Shiftless Deeds",
        "Nilitim's Grimoire Pg. 378": "enc Lvl 49 Allure",
        "Nilitim's Grimoire Pg. 379": "enc Lvl 49 Allure",
        "Nilitim's Grimoire Pg. 415": "enc Lvl 49 Blanket of Forgetfulness",
        "Nilitim's Grimoire Pg. 416": "enc Lvl 49 Blanket of Forgetfulness",
        "Nilitim's Grimoire Pg. 449": "enc Lvl 49 Reoccurring Amnesia",
        "Nilitim's Grimoire Pg. 450": "enc Lvl 49 Reoccurring Amnesia",
        ### Mage
        "Words of Transcendence": "mag Lvl 24 Cornucopia/Everfount",
        "Words of Dimension": "mag Lvl 24 Air/Fire/Water Pet",
        "Words of Coercion": "mag Lvl 29 Earth/Water Pet",
        "Words of Duress": "mag Lvl 34 Air/Fire Pet",
        "Words of Convocation": "mag Lvl 39 Earth/Water Pet",
        "Words of Incarceration": "mag Lvl 44 Air/Earth/Water Pet",
        "Words of Bondage": "mag Lvl 49 Air/Fire/Water Pet",
        ### Necro
        "Words of the Sentient (Beza)": "nec Lvl 24 Intensify Death",
        "Words of Recluse": "nec Lvl 24 Intensify Death",
        "Words of Absorption": "nec Lvl 24 Intensify Death/Lvl 20 Harmshield",
        "Words of Possession": "nec Lvl 16 Voice Graft/Lvl 24 Haunting Corps",
        "Words of the Spoken": "nec Lvl 15 Voice Graft",
        "Words of Materials": "nec Lvl 16 Hungry Earth",
        "Words of Spirit": "Lnec vl 16 Hungry Earth",
        "Words of Refuge": "nec Lvl 20 Harmshield",
        "Words of Detachment": "nec Lvl 24 Haunting Corps",
        "Words of Allure": "nec Lvl 24 Haunting Corps",
        "Words of Purification": "nec Lvl 29 Renew Bones",
        "Words of the Incorporeal": "nec Lvl 29 Renew Bones",
        "Words of Acquisition (Azia)": "nec Lvl 29 Renew Bones",
        "Words of Motion": "Lnec vl 34 Call of Bones",
        "Words of Neglect": "nec Lvl 34 Call of Bones",
        "Words of Endurance": "nec Lvl 34 Call of Bones",
        "Words of Abatement": "nec Lvl 34 Surge of Enfeeblement",
        "Words of Cazic-Thule": "nec Lvl 34 Surge of Enfeeblement",
        "Words of Efficacy": "nec Lvl 34 Surge of Enfeeblement",
        "Words of Dark Paths": "nec Lvl 34 Invoke Shadow",
        "Words of Suffering": "nec Lvl 34 Invoke Shadow",
        "Words of Haunting": "nec Lvl 34 Invoke Shadow",
        "Words of the Psyche": "nec Lvl 44 Dead Man Floating",
        "Words of Burnishing": "nec Lvl 44 Dead Man Floating",
        "Words of Requisition": "nec Lvl 49 Invoke Death",
        "Words of Acquisition (Beza)": "nec Lvl 49 Invoke Death",
        "Words of the Ethereal": "nec Lvl 49 Lich",
        "Words of Grappling": "nec Lvl 49 Bond of Death",
        "Words of Odus": "nec Lvl 49 Bond of Death",
        ### Wizard
        "Rune of Nagafen": "wiz Lvl 16 Pillar of Fire",
        "Rune of Proximity": "wiz Lvl 16 Pillar of Fire",
        "Rune of Fulguration": "wiz Lvl 16 Project Lightning",
        "Rune of Periphery": "wiz Lvl 16 Project Lightning",
        "Rune of Al'Kabor": "wiz Lvl 20 Fire Spiral of Al'Kabor/Lvl 29 Shock Spiral of Al'Kabor/Lvl 39Force Spiral of Al'Kabor",
        "Rune of Velious": "wiz Lvl 20 Fire Spiral of Al'Kabor",
        "Rune of Disassociation": "wiz Lvl 24 Cast Force",
        "Rune of Presence": "wiz Lvl 24 Cast Force",
        "Rune of Trauma": "wiz Lvl 24 Column of Lightning",
        "Rune of Xegony": "wiz Lvl 24 Column of Lightning/Lightning Storm/Lvl 29 Energy Storm",
        "Rune of Karana": "wiz Lvl 24 Lightning Storm/Energy Storm",
        "Rune of Fulguration": "wiz Lvl 29 Energy Storm",
        "Rune of the Helix": "wiz Lvl 29 Shock Spiral of Al'Kabor",
        "Rune of Rallos Zek": "wiz Lvl 29 Shock Spiral of Al'Kabor",
        "Rune of Banding": "wiz Lvl 34 Circle of Force",
        "Rune of the Catalyst": "wiz Lvl 34 Circle of Force",
        "Rune of Concussion": "wiz Lvl 34 Circle of Force/Lava Storm/Lvl 49 Wrath of Al'Kabor",
        "Rune of the Cyclone": "wiz Lvl 34 Lava Storm",
        "Rune of Solusek Ro": "wiz Lvl 34 Lava Storm",
        "Rune of Conception": "wiz Lvl 34 Thunderclap",
        "Rune of Contortion": "wiz Lvl 34 Thunderclap",
        "Rune of Howling": "wiz Lvl 34 Thunderclap",
        "Rune of the Helix": "wiz Lvl 39 Force Spiral of Al'Kabor",
        "Rune of Infraction": "wiz Lvl 39 Force Spiral of Al'Kabor",
        "Rune of Attraction": "wiz Lvl 44 Gravity FLux",
        "Rune of the Inverse": "wiz Lvl 44 Gravity FLux",
        "Rune of Rathe": "wiz Lvl 44 Gravity FLux",
        "Rune of the Astral": "wiz Lvl 49 Supernova/Ice Comet",
        "Rune of Impetus": "wiz Lvl 49 Supernova",
        "Rune of Ap'Sagor": "wiz Lvl 49 Wrath of Al'Kabor",
        "Rune of Frost": "wiz Lvl 49 Ice Comet"
}
